# Generated by Django 5.2 on 2026-01-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_learninggoal_studystreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='last_studied',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
