# Generated by Django 6.0.1 on 2026-01-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_learninggoal_ai_solution_alter_task_task_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='is_oauth',
        ),
        migrations.RemoveField(
            model_name='platformaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='platformaccount',
            name='platform_user_id',
        ),
        migrations.RemoveField(
            model_name='platformaccount',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='platform',
            name='uses_public_api',
            field=models.BooleanField(default=True),
        ),
    ]
