# Generated by Django 6.0.1 on 2026-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_platform_is_oauth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='leetcode_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='leetcode_xp',
            field=models.IntegerField(default=0),
        ),
    ]
