# Generated by Django 6.0.1 on 2026-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userstats_leetcode_solved_userstats_leetcode_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='codeforces_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='gfg_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='github_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='hackerrank_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
