# Generated by Django 6.0.1 on 2026-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userstats_codeforces_username_userstats_gfg_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='codeforces_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='codeforces_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='gfg_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='gfg_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='hackerrank_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='hackerrank_xp',
            field=models.IntegerField(default=0),
        ),
    ]
