# Generated by Django 6.0.1 on 2026-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_userstats_codeforces_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
