# Generated by Django 6.0.1 on 2026-01-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_note_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learninggoal',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='learningtrack',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-study_date']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('track', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'name')},
        ),
    ]
